<?php
/**
 * @category   Reload
 * @package    Reload_Seo
 * @copyright  Copyright (c) 2013-2015 AndCode (http://www.andcode.nl)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php 
if($this->getScore() != null) { 
//Only show the html and javascript if the score object is not null.
?>
<div id="reload-seo-scores" class="reload-seo-scores">
	<div class="seo-results">
		<div class="base-score seo-box">
			<ul class="messages" <?php if($this->showDisabledMessage()) { echo 'style="display: block;"'; } ?>>
				<li class="notice-msg">
					<ul>
						<li>
							<span><?php echo Mage::helper('reload_seo')->__('This product has been disabled, the SEO-score will not be calculated.'); ?></span>
						</li>
					</ul>
				</li>
			</ul>
			<p><?php echo Mage::helper('reload_seo')->__('Based on our information we have calculated the following SEO-score:'); ?></p>
			<span class="seo-score" style="background-color: <?php echo $this->getScore()->getColor(); ?>;"><?php echo $this->getScore()->getScore(); ?></span>
			<button type="button" class="seo-toggle-button">Hide</button>
		</div>
		<div class="seo-rules">
			<table cellpadding="0" cellspacing="0">
				<tbody>
					<?php foreach($this->getScore()->getRulesCollection() as $rule) { ?>
						<tr class="seo-rule">
							<td class="indicator"><div class="indicator-dot" style="background-color: <?php echo $rule->getStatus(); ?>;"></div></td>
							<td><?php echo $rule->getTitle(); ?></td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<?php $fieldMapping = Mage::helper('reload_seo')->getFieldMappings($this->getScore()->getType()); ?>
<script type="text/javascript">

reloadseo.url = '<?php echo $this->getUrl('reload_seo/adminhtml_seo/ajax', array('type' => $this->getScore()->getType(), 'reference' => $this->getScore()->getReferenceId())); ?>';
reloadseo.type = '<?php echo $this->getScore()->getType(); ?>';

reloadseo.vars.type = '<?php echo $this->getScore()->getType(); ?>';
reloadseo.vars.field_mapping = <?php echo json_encode($fieldMapping); ?>;
reloadseo.vars.form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';

reloadseo.init();
</script>
<?php } ?>